// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy86OM86MZ4-H6zlPDTolLQhgy33pQ7dU',
    appId: '1:766658595244:web:5aaa9554eb50b7172ad209',
    messagingSenderId: '766658595244',
    projectId: 'hour-stay',
    authDomain: 'hour-stay.firebaseapp.com',
    storageBucket: 'hour-stay.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4vPSs432IPgUHT-OMO8MdFmMRgE8S9sQ',
    appId: '1:766658595244:android:2c00ad824995957d2ad209',
    messagingSenderId: '766658595244',
    projectId: 'hour-stay',
    storageBucket: 'hour-stay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJoQlDBMzmjNt65w19tKJNS9Irhb7vp00',
    appId: '1:766658595244:ios:7521e07cb78efb7a2ad209',
    messagingSenderId: '766658595244',
    projectId: 'hour-stay',
    storageBucket: 'hour-stay.firebasestorage.app',
    iosBundleId: 'com.hourstay.hms.hourStayMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJoQlDBMzmjNt65w19tKJNS9Irhb7vp00',
    appId: '1:766658595244:ios:7521e07cb78efb7a2ad209',
    messagingSenderId: '766658595244',
    projectId: 'hour-stay',
    storageBucket: 'hour-stay.firebasestorage.app',
    iosBundleId: 'com.hourstay.hms.hourStayMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCy86OM86MZ4-H6zlPDTolLQhgy33pQ7dU',
    appId: '1:766658595244:web:2a6d1116d52b14322ad209',
    messagingSenderId: '766658595244',
    projectId: 'hour-stay',
    authDomain: 'hour-stay.firebaseapp.com',
    storageBucket: 'hour-stay.firebasestorage.app',
  );
}
